          path: app/build/outputs/apk/full/release/*.apk
name: Branch CI

on:
  workflow_dispatch:

jobs:
  build:
    name: Build AAPS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE }}" | base64 -d > app/release.jks

      - name: Generate Navigation & Sources
        run: ./gradlew generateFullReleaseSources --no-daemon
        env:
          GRADLE_OPTS: "-Xmx4096m -XX:MaxMetaspaceSize=1024m"

      - name: Build APK
        run: ./gradlew assembleFullRelease --no-daemon -x lint -x test
        env:
          GRADLE_OPTS: "-Xmx4096m -XX:MaxMetaspaceSize=1024m"
          RELEASE_STORE_FILE: release.jks
          RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
          RELEASE_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
          RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AAPS-Release-APK
          path: app/build/outputs/apk/full/release/*.apk
